- name: Check that database is running
  hosts: east-node1
  tasks:
    - name: Check for output from database
      ansible.builtin.command: "{{ yb_executable_dir }}/ysqlsh -h {{ ansible_host }} -c 'select version()'"
      register: dbversion
      until: "dbversion is not failed"
      retries: 10
      delay: 1

- name: Ensure database on east
  hosts: east-node1
  tasks:
    - name: Create ghcn database
      ansible.builtin.command: "{{ yb_executable_dir }}/ysqlsh -h {{ ansible_host }} -c 'create database ghcn'"
      ignore_errors: true

- name: Ensure data is available to create tables in scenarios
  hosts: east-node1
  tasks:
    - name: Download stations file
      ansible.builtin.get_url:
        url: https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-stations.txt
        dest: /tmp/stations.txt
        mode: "0775"

    - name: Download countries file
      ansible.builtin.get_url:
        url: https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-countries.txt
        dest: /tmp/countries.txt
        mode: "0775"

    - name: Download states file
      ansible.builtin.get_url:
        url: https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-states.txt
        dest: /tmp/states.txt
        mode: "0775"

    - name: Download inventory file
      ansible.builtin.get_url:
        url: https://www.ncei.noaa.gov/pub/data/ghcn/daily/ghcnd-inventory.txt
        dest: /tmp/inventory.txt
        mode: "0775"
